development: &common
  adapter: postgresql
  username: rooblog
  password: RooBlog100!
  min_messages: WARNING
  reconnect: true
  pool: 50
  encoding: unicode
  database: rooblog_development
  host: localhost

production:
  <<: *common
  database: rooblog_production

staging:
  <<: *common
  database: rooblog_staging

test:
  <<: *common
  database: rooblog_test

